# Generated by Django 4.2.1 on 2023-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
