# Generated by Django 4.2.1 on 2023-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_videos_alter_article_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Videos",
        ),
        migrations.AlterField(
            model_name="article",
            name="img",
            field=models.FileField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
